[project]
name = "discount-coupon-bot"
version = "0.1.0"
description = "Telegram bot for discount coupons"
requires-python = ">=3.8"
dependencies = [
    "aiogram>=3.2.0",
    "python-dotenv>=1.0.0"
]
